// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace SchoolManagement.Data.SchoolManagement
{
    [DbContext(typeof(SchoolManagementDbContext))]
    public partial class SchoolManagementDbContextModel : RuntimeModel
    {
        static SchoolManagementDbContextModel()
        {
            var model = new SchoolManagementDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static SchoolManagementDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
