// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace SchoolManagement.Data.SchoolManagement
{
    public partial class SchoolManagementDbContextModel
    {
        partial void Initialize()
        {
            var classRoom = ClassRoomEntityType.Create(this);
            var menu = MenuEntityType.Create(this);
            var news = NewsEntityType.Create(this);
            var parents = ParentsEntityType.Create(this);
            var schedule = ScheduleEntityType.Create(this);
            var scheduleTime = ScheduleTimeEntityType.Create(this);
            var schoolDetail = SchoolDetailEntityType.Create(this);
            var semester = SemesterEntityType.Create(this);
            var student = StudentEntityType.Create(this);
            var subject = SubjectEntityType.Create(this);
            var teacher = TeacherEntityType.Create(this);
            var transcript = TranscriptEntityType.Create(this);
            var violation = ViolationEntityType.Create(this);

            ClassRoomEntityType.CreateForeignKey1(classRoom, schoolDetail);
            ClassRoomEntityType.CreateForeignKey2(classRoom, teacher);
            MenuEntityType.CreateForeignKey1(menu, menu);
            ScheduleEntityType.CreateForeignKey1(schedule, classRoom);
            ScheduleEntityType.CreateForeignKey2(schedule, scheduleTime);
            ScheduleEntityType.CreateForeignKey3(schedule, semester);
            ScheduleEntityType.CreateForeignKey4(schedule, subject);
            StudentEntityType.CreateForeignKey1(student, classRoom);
            StudentEntityType.CreateForeignKey2(student, parents);
            SubjectEntityType.CreateForeignKey1(subject, teacher);
            TranscriptEntityType.CreateForeignKey1(transcript, semester);
            TranscriptEntityType.CreateForeignKey2(transcript, student);
            TranscriptEntityType.CreateForeignKey3(transcript, subject);
            ViolationEntityType.CreateForeignKey1(violation, student);

            ClassRoomEntityType.CreateAnnotations(classRoom);
            MenuEntityType.CreateAnnotations(menu);
            NewsEntityType.CreateAnnotations(news);
            ParentsEntityType.CreateAnnotations(parents);
            ScheduleEntityType.CreateAnnotations(schedule);
            ScheduleTimeEntityType.CreateAnnotations(scheduleTime);
            SchoolDetailEntityType.CreateAnnotations(schoolDetail);
            SemesterEntityType.CreateAnnotations(semester);
            StudentEntityType.CreateAnnotations(student);
            SubjectEntityType.CreateAnnotations(subject);
            TeacherEntityType.CreateAnnotations(teacher);
            TranscriptEntityType.CreateAnnotations(transcript);
            ViolationEntityType.CreateAnnotations(violation);

            AddAnnotation("ProductVersion", "7.0.10");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
